language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: "N5m2vyqRnmTG0FQRPfWz2J+zIWAMbNqrV2BLKChhzQpiExXXXoIUifttZLQ8WNL8zD+JdrOzOYTeIzeJb0wLnJdTGpOT4sFXRuzqNUBgNtUVCSB11QBTVqMzEhvah76pF4A4QwzSr4+NDIyEVS68D8lVF9UkKHGeeR/V8mfihpAPF9xY6KVUN7lgF3YwTJpvxWanSYnoAZFcIIxEcmRbuqDR1RUOcAEOPkh3ckJPiwULKOWF9kqXM/BkE1BQH3IoowRqM/ygj33cxD1nm1o1i4yiIKWMPUxi2d8eY4HZ9klcccihIQ6ELVZ+gIN/QSoTRiMMnz+XVU+KKJggOoB5jyX1g0qEVFZp1uzcldFjZEabPqZiey225RU2nlZAikL1v04UokRL6Qptq24E0Ll6jOwIddLzKMba7Gb6j789ofllLYOJtfqUfcpNWJ3rgBBn6R8A2gqgLtdje6ac0DTxD6Rh94ZZ8BeAGpa3BkSDtV5LQzvWrtCzUChL/DNmYjGLDcDWIFflWWWMNMgQQio8XXPBRZNUAs1l79ECg1osPAdaCIPiLm4Qtg3OIXEjVrKXQsJOO3eNB3q+7szVia+UCFKT8pgPJpIjL3YsNnhYtSww7PqrC9ASka1eyacIJK4FEf6kI8ZpdCtTGlF5nmb13kU+5TJg2YJvRCrdv5tYq3c="
  app:
  run: rails db:migrate
